### ISSUE TITLE
[Feature] Add PlayerDoubleJumpEvent to API

### ISSUE THREAD

**Issue by Drc-DEV** [TreyRuffy/TreysDoubleJump#15]
In order to make the plugin compatible with any setup, such an event should exist as a cancellable event, called before the double jump is applied to the player, so that it can be cancelled in some situations, like pvp, no-flight areas etc.

**Comment by TreyRuffy** [comment]
Yeah I will look into it. It is going to take a little bit just because of school but I will try to find time to add this for you.

**Comment by TreyRuffy** [comment]
Alright, I am almost finished with adding it. I just need to add the documentation and a couple more things, but I will add a new branch if you want to try it now.

**Comment by TreyRuffy** [comment]
Added in #17
