### ISSUE TITLE
[Bug]  Can't double jump on one block

### ISSUE THREAD

**Issue by Shuboh** [TreyRuffy/TreysDoubleJump#18]
**Describe the bug**
when you are on a block that has nothing under it, it doesn't double jump

**To Reproduce**
just make a bridge or a platform with a floor of 1 thickness, then try to double jump multiple times

**Expected behavior**
just a double jump when i'm on the ground

**Version Information (please complete the following information):**
 - Server Type: spigot
 - Version 1.15.2

**Comment by TreyRuffy** [comment]
I just replicated the bug and will be patching it within the next hour.
