### ISSUE TITLE
[Bug] GroundPound Issues

### ISSUE THREAD

**Issue by slooshied** [TreyRuffy/TreysDoubleJump#19]
**Describe the bug** 

_2 BUGS_
GroundPound is able to be used in every world despite being disabled in the config. 

GroundPound causes players who are flying to be shot to the ground when trying to lower their elevation

**To Reproduce**
Do /groundpound in a world where /doublejump is disabled

With groundpound enabled during flight, press shift.

**Expected behavior**
Ground pound should not work in a world clarified disabled in the config.

Players should be able to lower their flight elevation without being shot to the ground upon having groundpound enabled during flight. 

**Screenshots**
![bug](https://user-images.githubusercontent.com/70556905/103472017-90acdb00-4d4d-11eb-848c-ecbb7c385def.gif)

**Version Information (please complete the following information):**
 - Server Type: Paper
 - Version: 1.16.2

**Additional context**
None.

**Comment by TreyRuffy** [comment]
I have replicated the first one bug I cannot seem to get the second one. Can I have your configuration file?
