### ISSUE TITLE
Enabling double jump doesn't give you fall damage

### ISSUE THREAD

**Issue by YeetingYeeterz** [TreyRuffy/TreysDoubleJump#25]
**Describe the bug**
While enabling double jump, fall damage turns off, even disabling NoFall won't help.

**To Reproduce**
Toggling /dj produced said bug.

**Expected behavior**
Falling off a high place or a tall ledge should damage players with double jump on.

**Screenshots**
It's a video but I hope this helps on what I'm describing.
https://mega.nz/file/wHZwWJ7L#YSqEDrw0F3OIE-jmrjM4m76JqzdtZ1_9fUCwFi964NA

**Version Information (please complete the following information):**
 - Server Type: Spigot
 - Version 1.16.5

**Additional context**
None

**Comment by TreyRuffy** [comment]
What other plugins are on the server? Also, are there any errors in the console?

**Comment by YeetingYeeterz** [comment]
> What other plugins are on the server? Also, are there any errors in the console?

There's no other plugins that changes the vanilla movement or changes the behavior of the server except double jump, and I can't seem to find any errors in the console

**Comment by TreyRuffy** [comment]
Can I see your configuration file then?

**Comment by YeetingYeeterz** [comment]
> Can I see your configuration file then?
> 
> Also, what are your permissions? Are you opped?

I am opped but the same thing happens to players who aren't opped and have the double jump and groundpound permission only, here is the config
[config.txt](https://github.com/TreyRuffy/TreysDoubleJump/files/6105240/config.txt)

**Comment by TreyRuffy** [comment]
Is it only right after you type /dj?

**Comment by YeetingYeeterz** [comment]
> Is it only right after you type /dj? 

Yes.

**Comment by TreyRuffy** [comment]
I have looked into it and I do not think it's possible to do. I can't believe I haven't noticed it until now, but I will continue looking for solutions.

If anyone reading this can think of one, the reason it does not work is because when [setAllowFlight](https://github.com/TreyRuffy/TreysDoubleJump/blob/ceb85674c704ff70721873f8aff8b8c1e0f72e6e/TreysDoubleJump/src/main/java/me/treyruffy/treysdoublejump/events/DoubleJump.java#L188) is set to true, it does not give fall damage.

**Comment by TreyRuffy** [comment]
I have created a PaperMC pull request in order to fix this problem. You can check it out at PaperMC/Paper#5357.

**Comment by TreyRuffy** [comment]
This was fixed in 2.6.6 if you use Purpur!
