### ISSUE TITLE
[Bug] Wrong color code if [] brackets are in message

### ISSUE THREAD

**Issue by S4MON1X** [TreyRuffy/TreysDoubleJump#26]
**Describe the bug**
When I set the any message to "&8[&bSystem&8]&r sometext" it will broke the reset code and sets color from color code in brackets 

**To Reproduce**
Just type the thing what i said

**Expected behavior**
It should reset formatting not use color

**Screenshots**
![2021-03-23_13 59 32](https://user-images.githubusercontent.com/55529446/112150228-24b97080-8be0-11eb-8b88-c996cdb16bee.png)

**Version Information (please complete the following information):**
 - Server Type: PaperSpigot
 - Version 1.8.9

**Additional context**
Just to say, that error is in any message.

**Comment by TreyRuffy** [comment]
Can I see your config.yml file?
