### ISSUE TITLE
OP BUG

### ISSUE THREAD

**Issue by SladeHazard** [TreyRuffy/TreysDoubleJump#32]
People that aren't op and have tdj.* permission can't double jump infinitely. the option is enabled in cfg. server 1.12.2

**Comment by TreyRuffy** [comment]
Can I see your config file

**Comment by SladeHazard** [comment]
https://pastebin.com/W8NeEsCA

**Comment by TreyRuffy** [comment]
I'm unable to reproduce it, after trying several times. You can contact me on Discord at `TreyRuffy#0001` and I will personally help you. I will close this for now unless I see that it is, in fact, not just you.
