### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Grentenville** [TreyRuffy/TreysDoubleJump#33]
My console is being spammed, in the console i can only identify your plugin, when the only player with the double jump permission exit the console spam stops.
Here is some part of the spam https://hastebin.com/avobafupuf.md, i can send the full log if needed, but it got 50MB in just some minutes
I'm not entirely sure how to reproduce, the only information i know is the console spam when someone have the permission and don't even need to jump, only be walk the console is spammed

**Expected behavior**
The console don't spam

**Version Information (please complete the following information):**
 - Server Type: waterfall, running on purpur 1346
 - Version 1.17.1

**Comment by TreyRuffy** [comment]
Your configuration file has an incorrect  value. It includes the value `BOSSARENA` when it isn't supposed to. Can you send me the config file?
