### ISSUE TITLE
Add support for fly-mode? (Wanted feature)

### ISSUE THREAD

**Issue by Nesseley** [TreyRuffy/TreysDoubleJump#5]
Hey man, would be awesome if you added /fly to this plugin. (with a perm) or detect if a player already has fly toggled on.
Since my mods can't use /fly they will only double jump (it owerwrights /fly)
- Nesseley

**Comment by TreyRuffy** [comment]
Adding in the next release (1.1) later today!

**Comment by Nesseley** [comment]
Even with perm tdj.fly I still cannot fly :/ 
Not sure why eighter, but I don't even need to give permissions for the plugin to work on my server?
Does this not support bungeeperms?

**Comment by TreyRuffy** [comment]
Adding in a future version. Almost done with it.
