### ISSUE TITLE
Compatibility with ViaVersion and ProtocolSupport

### ISSUE THREAD

**Issue by Eufranio** [TreyRuffy/TreysDoubleJump#6]
Seems this plugin is incompatible with both ViaVersion and ProtocolSupport, I have a 1.8.8 server with them, and it's not working.

Help?

**Comment by TreyRuffy** [comment]
I will look into it soon!

**Comment by TreyRuffy** [comment]
I do not believe it is my plugin, rather ProtocolSupport was made for 1.10 not 1.8 and is not backwards compatible.
