### ISSUE TITLE
Issues When Entering Spectator Gamemode

### ISSUE THREAD

**Issue by heckabecca** [TreyRuffy/TreysDoubleJump#8]
I'm having the issue, when I go into spectator mode, where my character just bounces up and down repeatedly. Creative and survival are fine, when I have fly enabled I can fly with no issues. But going into Spectator things just kinda freak out. Everything is normal if I remove the plugin, or am in one of the other modes.

**Comment by heckabecca** [comment]
I must be tripping. Things are all fine now. Super puzzled but the issue is gone.

**Comment by TreyRuffy** [comment]
Awesome! I was like "Hmm, I cannot seem to find how you would have done that" xP
