### ISSUE TITLE
The double jump command is broken

### ISSUE THREAD

**Issue by DrOreo002** [TreyRuffy/TreysDoubleJump#9]
Okay so, I'm using the latest version of tdj. But the command seems not working for me, when I use /tdj toggle its not showing anything :/, help?

**Comment by TreyRuffy** [comment]
I am not sure... What are your plugins? Also, what does your **/ver** say? It seems to be working for me..

**Comment by DrOreo002** [comment]
Same. I'm using the latest version of spigot tho (1.12 july 26)

**Comment by TreyRuffy** [comment]
Do you get an error in console?
